# Generated by Django 4.2 on 2025-07-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_options_category_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_certificate',
            field=models.BooleanField(default=False, verbose_name='Является сертификатом'),
        ),
    ]
